### ISSUE TITLE
Wordpress content updates for CFP

### ISSUE THREAD

**Issue by kcomandich** [osbridge/planning#123]
1) Update Call for Proposals page with Proposal button, and new talks we like:
http://opensourcebridge.org/call-for-proposals/
Talks listed are from a couple years ago now.
Also we can add back in text about the deadline and acceptance notifications date, I removed it until we've decided these.

2) This page also includes the CFP deadline:
http://opensourcebridge.org/get-involved/for-user-groups/

3) Create this page: http://opensourcebridge.org/y2015 (note the y before the year) once OCW event is created.

**Comment by kcomandich** [comment]
Number 3 was done at some point.

**Comment by akf** [comment]
Kirsten and I finished this today!
