### ISSUE TITLE
Put 2015 sponsors on front page sidebar (done: create 2015 Sponsorship page)

### ISSUE THREAD

**Issue by kcomandich** [osbridge/planning#126]
Edit in Wordpress.
Side bar is edited at: Appearance > Widgets > Sponsors sidebar 
http://opensourcebridge.org/

**Comment by kcomandich** [comment]
Soon we can do this, as we have these sponsors:
* Google - we have purchase order. wait until their payment?
* Mandrill - paid
* Barewalls - paid

**Comment by christi3k** [comment]
Historically we have posted sponsor logos when we get signed sponsor agreement, assuming in good faith that payment will follow. I personally like giving sponsors the benefit of the doubt and maximizing their exposure.

**Comment by akf** [comment]
I'll see if I can put these on the site tonight, then!

**Comment by akf** [comment]
2015 sponsors are in sidebar. I'll add more as they come in.

**Comment by akf** [comment]
I missed the bit about making sure all the sponsors in the 2014 sidebar were also on the 2014 Sponsors page. Fortunately archive.org has the sidebar for me: https://web.archive.org/web/20150215173454/http://opensourcebridge.org/

**Comment by akf** [comment]
And the 2014 historical sponsors page is done.
