### ISSUE TITLE
2015 Diversity Outreach

### ISSUE THREAD

**Issue by christi3k** [osbridge/planning#130]

**Comment by akf** [comment]
@shawnacscott, could you review that brainstorm list and see if there's anything that we should still follow up on? I'm closing issues about promoting the CFP, but there are some things on this list that are a more general.

**Comment by shawnacscott** [comment]
I don't think there's anything (except maybe childcare?) hat'so not documented elsewhere, but this was mostly @capnleela, so she should probably check it out too!
