### ISSUE TITLE
Solicit talks from speakers from underrepresented groups for 2015

### ISSUE THREAD

**Issue by brainwane** [osbridge/planning#136]
Think of awesome speakers from diverse backgrounds whom you'd love to see talks from at OSB 2015.  Email them telling them about OSB, telling them to watch for the call for proposals in January, and requesting that they start thinking of a talk to propose.

It would especially be great to solicit talks from speakers from underrepresented groups in open culture/tech with regard to, for instance, class, ethnicity, sexuality, gender identity, primary spoken language, geographic region, military veteran status, ability and neurodiversity.

(A sub-task of #130. This is a task that would be good to work on during a work sprint like [the hackathon on December 13](http://calagator.org/events/1250467398). This task is one that multiple people can each do separately.)

**Comment by brainwane** [comment]
I've now improved http://stumptownsyndicate.org/wiki/Open_Source_Bridge/2015/Speaker_Outreach with more names and a wiki table so we can better track who's reached out to whom.

**Comment by znmeb** [comment]
What's the protocol? I don't have email addresses for most of the ones I've suggested. Is there a suggested wording?

**Comment by brainwane** [comment]
znmeb, I think if you want to reach out to a speaker, you should find their email address and then -- once the call for talks is up and open -- send them an email going something like:

> Subject: Open Source Bridge call for talks open - interested in speaking?

> Dear [name]:

> Hello! I heard about you via [thing] and thought you were interested in some things that might also make you interested in Open Source Bridge. It's a nonprofit conference about [explanation of OSB that will make sense to that person], where people from across these communities come together to swap tips and inspire each other. It'll be [dates] in Portland, Oregon.
> [link to Call For Talks]
> Would you be interested in proposing a talk about [topic that person is an expert in]? Or perhaps another topic?
> [reason you particularly like Bridge -- quality of talks, opportunity to talk with friendly people from lots of disciplines, etc.]
> Hope you'll consider proposing a talk by [deadline], or maybe just attending.  Best wishes and best of luck with your work!

Then, once that email is sent, change the relevant cells in [the outreach table](http://stumptownsyndicate.org/wiki/Open_Source_Bridge/2015/Speaker_Outreach) so people know someone has already sent them a note.

**Comment by brainwane** [comment]
The call for talks is open http://opensourcebridge.org/blog/2015/01/submit-your-2015-proposals-today/ -- znmeb and others, please feel free to start emailing potential speakers using the template I [posted](https://github.com/osbridge/planning/issues/136#issuecomment-68904520) and then say in [the outreach spreadsheet](http://stumptownsyndicate.org/wiki/Open_Source_Bridge/2015/Speaker_Outreach) that you've done so! Thanks!

**Comment by brainwane** [comment]
Could this be something we work on during the Feb. 7th sprint (#152)?

**Comment by akf** [comment]
Closing because the CFP is about to close.
