### ISSUE TITLE
Get more session slides/notes on the Open Source Bridge 2014 wiki

### ISSUE THREAD

**Issue by brainwane** [osbridge/planning#137]
Go through [the list of wiki pages for Open Source Bridge 2014](http://opensourcebridge.org/wiki/Category:Open_Source_Bridge_2014_notes). (We have about 107 of them.) If the wiki page for a session doesn't include a link to the speaker's slides, notes, or wrapup blog entry, try to find slides/notes on the web and add a link, or contact the speaker and ask.

This is a task that would be good to work on during a work sprint like [the hackathon on December 13](http://calagator.org/events/1250467398). This task is one that multiple people can each do separately.

**Comment by reidab** [comment]
We did get these from speakers in 2014, but we're not sure where the files are. They may still be on the USB sticks, since we didn't get these handed out during the 2015 event. @christi3k did you end up with these after the 2015 conference, or @kcomandich did they end up in storage?
