### ISSUE TITLE
Fill out Mozilla sponsorship form

### ISSUE THREAD

**Issue by kcomandich** [osbridge/planning#143]
We need to fill out a form to ask Mozilla to sponsor us, as we did last year.
* where is the form?
* can anyone do this?
* who will be contact person?

**Comment by akf** [comment]
I took a look at the form and wound up starting to fill it out, so I'm doing this. I'm not sure how to answer "will anyone from Mozilla be attending," so I'll make liberal use of the essay questions.

**Comment by akf** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1135414
