### ISSUE TITLE
Create a site to make videos searchable/discoverable?

### ISSUE THREAD

**Issue by kcomandich** [osbridge/planning#145]
pyvideo.org as an example?

part of the OSB site?

**Comment by akf** [comment]
I'm putting this in the "After the conference" milestone, but maybe this could be a hacker lounge or unconference topic.

**Comment by brainwane** [comment]
The body of knowledge in OSBridge recordings is awesome and I would personally like it if there were a site or some kind of functionality within the OSBridge wiki that made it easier to discover, search, and so on.

**Comment by znmeb** [comment]
How are the videos managed now? Can we leverage YouTube? Are there reasons *not* to leverage YouTube? ;-)

**Comment by brainwane** [comment]
@znmeb you make a good point. :) I guess I would like a few different things:

* FLOSS: in accordance with FLOSS values, I know the goal is to eventually upload high-quality versions of past recordings to archive.org (@vmbrasseur is also in favor of this I think!)
* discoverabillity: YouTube doesn't seem to allow tagging or similar lightweight structured ways to help people discover related videos. However it would be possible to make some more playlists -- like, topic playlists or track playlists (such as "all the business talks across all years").
