### ISSUE TITLE
CiviCRM needs spam deletion

### ISSUE THREAD

**Issue by kcomandich** [osbridge/planning#148]
Spam sent to our sponsorship email causes new contacts to be created in CiviCRM. If an email has any CCs, they all get added as contacts too.

So far I deleted a few contacts by first checking their Activity, to make sure they're not legitimate contacts, then deleting them one by one. Hopefully there's a better way.

**Comment by akf** [comment]
What's the status on this?

**Comment by reidab** [comment]
We really haven't figured out how to use CiviCRM effectively at all, so I'm going to call this a lost cause until we recommit to using it or find another solution.
