### ISSUE TITLE
Complete CfP opening checklist

### ISSUE THREAD

**Issue by kcomandich** [osbridge/planning#150]
Here is the website update checklist:
http://stumptownsyndicate.org/wiki/Open_Source_Bridge/Technology/Website_Updates_for_Opening_Proposals

and the OCW checklist:
https://github.com/osbridge/planning/issues/124

We could add all the emails, blog posts, tweets that go out, etc, and other tasks related to the Call for Proposals.

**Comment by brainwane** [comment]
I've added more - especially around [publicity](http://stumptownsyndicate.org/wiki/Open_Source_Bridge/Technology/Website_Updates_for_Opening_Proposals#Publicizing) - but would love a fresh set of eyes!

**Comment by brainwane** [comment]
I'm going to call this done. :)
