### ISSUE TITLE
Volunteer worksprint: January 3rd @ Epicodus, 1 - 5 PM

### ISSUE THREAD

**Issue by kcomandich** [osbridge/planning#151]
co-located with the Calagator code sprint
http://calagator.org/events/1250467460

**Comment by znmeb** [comment]
today? like now? By the time I get there it'll be over! ;-)

**Comment by kcomandich** [comment]
Sorry, yeah, I think it turns out we didn't publicize it. :(

**Comment by kcomandich** [comment]
Done:
* create new OpenConferenceWare event for 2015 (#124)
* set current OCW event to 2015 (https://github.com/osbridge/open-source-bridge-proposals/commit/9b1fd4c86e4b5550e53c967c071cf0fe63a580e6)

**Comment by kcomandich** [comment]
Also done:
* Update shared fragments so that the top menu (on Wordpress, OCW, and the wiki) defaults to 2015, and contains all the right links for this year.

We're now ready to open proposals, once a deadline is chosen, and we can start publicizing it.
