### ISSUE TITLE
Finalize roles doc

### ISSUE THREAD

**Issue by akf** [osbridge/planning#154]
Check in on OSB core about roles, especially marketing/outreach. 

(From 2015-01-08 core team meeting.)

**Comment by brainwane** [comment]
I believe Amanda is now the owner of http://etherpad.stumptownsyndicate.org/p/osb-core-team-roles per our meeting http://stumptownsyndicate.org/wiki/Open_Source_Bridge/2015/Meetings/2015-01-15 . Is she on GitHub so we can assign?

**Comment by brainwane** [comment]
I think this is the same as #161 so I'm closing this as a duplicate. Thanks!
