### ISSUE TITLE
Reach out to contacts for sponsorship -- Kurt

### ISSUE THREAD

**Issue by akf** [osbridge/planning#155]
Adobe and Canonical.

(From 2015-01-08 core team meeting.)

**Comment by brainwane** [comment]
Kurt just said:
>  I followed up with Adobe this morning, no response yet. I will ping Canonical again also.

**Comment by neophiliac** [comment]
Got a note from Adobe; they are interested, and checking budget to see what level of sponsorship they want. I'm hopeful.

**Comment by capnleela** [comment]
What are the chances we can see if Divya from Adobe http://www.webvisionsevent.com/portland/speaker/manian-divya/?loc=portland-2015 would also want to speak at Bridge?

**Comment by neophiliac** [comment]
I'll ask my friend at Adobe to pass the request along.

**Comment by neophiliac** [comment]
I asked if it would be OK to post her address here so the people working on getting speakers could ask for referrals, and she agreed. So here it is. FYI, Sandrine is my friend at Adobe.

On 2015-02-15 22:23, Divya Manian manian@adobe.com wrote:
Hi Kurt!

Sandrine sent me your request. First of all, very kind of you to ask
me to speak at Open Source Bridge! I really wish I could speak, sadly
I am already speaking at too many events (1 in April, 1 in May, and 1
in Feb) so I am reluctant to accept more conferences to speak at. I
hope that is okay!

If you need suggestions for speakers, do let me know and I can send
some folks your way!

- divya

**Comment by neophiliac** [comment]
Would you like me to contact her, or is there a sponsorship group that might be more efficient?

From: Nora Calvillo calvillo@adobe.com
Sent: Wednesday, February 18, 2015 11:37 AM

We’ll be able to sponsor this event. We’d like to do the Citizen package for $3000.  Please have your friend contact me directly to work out the details.
 
Thanks!
Nora

**Comment by 1337807** [comment]
Contacted today

**Comment by reidab** [comment]
:+1:
