### ISSUE TITLE
Figure out who has HootSuite access

### ISSUE THREAD

**Issue by akf** [osbridge/planning#156]
And presumably, report back to the team. 

(From 2015-01-08 core team meeting.)

**Comment by znmeb** [comment]
Do you mean "who" has HootSuite access? Or "Hoo", as the clever owl-themed people like to say?

I've got an account, but anyone can get the free one like I have.

**Comment by akf** [comment]
Thanks. It should be "who." The question refers specifically to the HootSuite account @osbridge tweets from.

**Comment by christi3k** [comment]
The Syndicate board has access as the main account holder and it looks like a user 'osbridge' was setup and has access to the osbridge twitter. I don't have these credentials handy, but they can likely be looked up or reset.

**Comment by christi3k** [comment]
I've created a new email alias (social@) and hootsuite team for Open Source Bridge. This team has access to twitter and facebook pages for OSB.
