### ISSUE TITLE
Write blog post requesting keynote nominatons

### ISSUE THREAD

**Issue by akf** [osbridge/planning#159]
(TODO from 2015-01-15 core team meeting)

**Comment by christi3k** [comment]
very initial draft here: 
http://opensourcebridge.org/?p=3823&preview=true

you'll need an account on the blog to view
I'd love a quick read if someone has a moment. Is this the right approach? have I included all the pertinent info.

**Comment by akf** [comment]
It looks good to me. I think the title could be more compelling, and am trying to think of something better. 

I'm always thinking about trying to make these easier for people who skim. I think headings would be good for: 

* How to submit a nomination
* What we're looking for

... and I'd break out the "be sure to include" list into bullet points.

**Comment by akf** [comment]
Possible alternate titles: 

* Keynote speaker nominations wanted! (deadline January 31)
* Nominate a keynote speaker (deadline January 31)
* Open nominations for 2015 OS Bridge Keynotes (deadline January 31)

**Comment by christi3k** [comment]
http://opensourcebridge.org/blog/2015/01/keynote-nominations-wanted-deadline-january-31/
