### ISSUE TITLE
Write/send an email about the CFP and keynote nominations

### ISSUE THREAD

**Issue by akf** [osbridge/planning#160]
(TODO from 2015-01-15 core team meeting)

**Comment by christi3k** [comment]
Blocked by #159

**Comment by christi3k** [comment]
This is ready to go in Mailchimp. All that's needed is a link from the blog post in issue #159. Gonna give a bit more time for folks to weigh in on that.

**Comment by christi3k** [comment]
Email queued for delivery tomorrow ~9:30am PT.
