### ISSUE TITLE
Review, improve, and finalize documentation of core volunteer team roles 

### ISSUE THREAD

**Issue by akf** [osbridge/planning#161]
http://etherpad.stumptownsyndicate.org/p/osb-core-team-roles

(TODO from 2015-01-15 core team meeting)

**Comment by christi3k** [comment]
FYI we've moved this content to the wiki: http://stumptownsyndicate.org/wiki/Open_Source_Bridge/Roles

Please comment and edit there instead of the etherpad.

**Comment by brainwane** [comment]
We'd like for each role page to include:
* What you need to do this job (pre-requisites)
* Responsibilities/Tasks
* Past roleholders
* Decisionmaking -- what you can do on your own versus what needs consensus (including what your budget is)
