### ISSUE TITLE
Prepare reusable email materials for wider user group outreach (re: CFP)

### ISSUE THREAD

**Issue by akf** [osbridge/planning#167]
(TODO from 2015-01-15 core team meeting)

**Comment by brainwane** [comment]
We may already have some past text we can use for this -- look for mail we sent last year!

**Comment by akf** [comment]
This is what Reid sent to pdxgroups last year: https://groups.google.com/d/msg/pdxgroups/UK6x9uCt5bY/SDRTh860hucJ (not sure whether that's public, probably)

I've pasted it into here for collaborative editing: http://etherpad.stumptownsyndicate.org/p/osb15-ugoutreach

**Comment by akf** [comment]
http://etherpad.stumptownsyndicate.org/p/osb15-ugoutreach has updated email drafts for local UG, non-local UG, and individual outreach.
