### ISSUE TITLE
Write and schedule many tweets advertising CFP + keynote nominations

### ISSUE THREAD

**Issue by christi3k** [osbridge/planning#169]
Please add tweet text ideas here. We'll schedule them with Hootsuite at a regular interval up until cfp deadline.

**Comment by reidab** [comment]
One idea for some of these is would be to track down useful articles about proposal writing and link to them. (e.g. http://alistapart.com/article/conference-proposals-that-dont-suck)

**Comment by brainwane** [comment]
We welcome first-time speakers, panels, workshops, tutorials, groups of lightning talks, and more http://opensourcebridge.org/blog/2015/01/submit-your-2015-proposals-today/

You can nominate yourself or someone else to keynote #osb15. Keynote speakers receive a $500 honorarium, travel help http://opensourcebridge.org/blog/2015/01/keynote-nominations-wanted-deadline-january-31/

allowedtoapply.tumblr.com/ You're not just allowed to apply, you're invited! Please submit your talk ideas by March 7 http://opensourcebridge.org/blog/2015/01/submit-your-2015-proposals-today/

Submit your talk for @osbridge http://opensourcebridge.org/blog/2015/01/submit-your-2015-proposals-today/ , read http://www.sarahmei.com/blog/2014/04/07/what-your-conference-proposal-is-missing/ , then revise your proposal :)

If you don't have an idea for your own #osb15 talk yet, tell us who should keynote! http://opensourcebridge.org/blog/2015/01/keynote-nominations-wanted-deadline-january-31/ Tell us by Jan. 31.

Please submit your #osb15 talk proposals by March 7th! http://opensourcebridge.org/blog/2015/01/submit-your-2015-proposals-today/ A HOWTO: http://alistapart.com/article/conference-proposals-that-dont-suck 

Calling for keynote nominations by Jan. 31: http://opensourcebridge.org/blog/2015/01/keynote-nominations-wanted-deadline-january-31/ Please help us decide who should keynote #osb15!

March 7th is the deadline for #osb15 talk submissions: http://opensourcebridge.org/blog/2015/01/submit-your-2015-proposals-today/ Check out last year's talks for ideas: http://opensourcebridge.org/events/2014/sessions

retweet https://twitter.com/jeremyckahn/status/322390046491688960 "Protip: Nobody is really "qualified" to give tech talks. We're all exploring and figuring it out. Just share what you've learned."

http://opensourcebridge.org/blog/2015/01/submit-your-2015-proposals-today/ Need help writing a talk proposal? http://weareallaweso.me/ has weekly online office hours, Tuesdays 10am PT

Example proposals from previous years: http://opensourcebridge.org/events/2014/proposals & other conferences http://www.oreilly.com/conferences/sample_proposals.html http://rhodesmill.org/brandon/2013/example-pycon-proposals/

A few more resources to help you submit an #osb15 talk: http://allowedtoapply.tumblr.com/post/75593818596/julia-evans-on-proposing-talks-a-series-of-tweets http://www.catehuston.com/blog/2014/06/06/my-4-step-plan-for-giving-a-talk/ http://speakup.io/

If your talk for #osb15 gets accepted, attendance is free; if rejected, you'll get the earlybird price http://opensourcebridge.org/blog/2015/01/submit-your-2015-proposals-today/

Haskell, PHP, C, storage, security, mentoring, bug triage, design, & whatever makes you a better open source citizen http://opensourcebridge.org/blog/2015/01/submit-your-2015-proposals-today/

Consider proposing a set of lightning talks or a moderated panel as an #osb15 session http://opensourcebridge.org/blog/2015/01/submit-your-2015-proposals-today/

You can submit several #osb15 proposals http://opensourcebridge.org/blog/2015/01/submit-your-2015-proposals-today/ -- improves your chances of having a talk selected!

**Comment by brainwane** [comment]
How do you make a living in open source? Tell us by submitting a talk for the Business track by March 7. opensourcebridge.org/blog/2015/01/submit-your-2015-proposals-today/ 

Show us the science behind the recipe; submit a deep-dive tech session in the Chemistry track by March 7. opensourcebridge.org/blog/2015/01/submit-your-2015-proposals-today/

Share tips, a tutorial, best practices, or a collaborative development session by submitting a Cooking track session opensourcebridge.org/blog/2015/01/submit-your-2015-proposals-today/

What makes open technology and culture communities effective? Submit a Culture track session by March 7th opensourcebridge.org/blog/2015/01/submit-your-2015-proposals-today/

Show us your most ingenious hacks, kludges, work-arounds, and duct-tape jobs, in the Hacks track: opensourcebridge.org/blog/2015/01/submit-your-2015-proposals-today/ Deadline March 7

**Comment by brainwane** [comment]
A few more:

http://opensourcebridge.org/events/2015bof/proposals If you want to discuss a topic at #osb15, submit a Birds of a Feather evening session!

The Birds of a Feather evening sessions are open to attendees with free Community Passes. http://opensourcebridge.org/events/2015bof/proposals Submit a BoF for #osb15!

**Comment by brainwane** [comment]
Lauren, I figure this item would fall to you now instead of Christie; please feel free to leave questions here or ask via email if you need any help!

**Comment by lehudgins** [comment]
I think these tasks will be assigned to me, but I have not yet received the information I need to log into our social media accounts or at least Hootsuite.

**Comment by znmeb** [comment]
I'll be tweeting some of these out over the next week. I can schedule them in Tweetdeck.

**Comment by lehudgins** [comment]
I'm happy to do scheduling and will put some of these into Facebook. (I don't want to have too many repetitive posts on our FB and Twitter accounts).

Are we using Tweetdeck or Hootsuite? Also I have not gotten the credentials for either.

**Comment by christi3k** [comment]
As a team, we're using Hootsuite. I think @znmeb is referring to his personal Tweetdeck.

@lehudgins I've created a social media team in Hootsuite and I'll send you details of how to access.

**Comment by akf** [comment]
Closing this because we must be just about done and the CFP closes tonight!
