### ISSUE TITLE
Create & send email & tweets about 2/7 work sprint

### ISSUE THREAD

**Issue by akf** [osbridge/planning#171]

**Comment by brainwane** [comment]
Send email to:
*    osbridge-core
*    osbridge Google Group
*    osbridge volunteers (depends on asking @ChrisFreeman how he is currently extracting the list of relevant addresses from the volunteer app)

Tweet from:
* @stumpsyn
* @osbridge

**Comment by ChrisFreeman** [comment]
For contacting volunteers;

Chris's current method is to use GMail (as volunteer@opensourcebridge.org ) to send to a manually copied list He has been maintaining. 

If mail chimp can set the SendAs and the ReplyTo volunteer@opensourcebridge.org that would work. Otherwise he's happy to sent it out through gmail.

**Comment by christi3k** [comment]
Yes, mailchimp can be configured to send from those email addresses.

Chris, can you prepare for me a csv file with those email addresses so I can update our list in MC? It should have two fields: Name and Email. 

The sooner I have this the sooner I can send out a mailing about next weekend's worksprint.

**Comment by ChrisFreeman** [comment]
Volunteer Email list created and shared via Dropbox with Christie and Amanda.

**Comment by shawnacscott** [comment]
Looking back at the notes, I'm unclear what was decided. Will emails and tweets about this go out, but only for those with technical expertise, or should this issue be closed until after Saturday, when planning for the next sprint will happen?

**Comment by christi3k** [comment]
We decided to keep the worksprint listed on calagator, but not advertise it more widely than that. I think we can close this issue and create another later, for the next work sprint.
