### ISSUE TITLE
Contact breweries to ask about drink sponsorship

### ISSUE THREAD

**Issue by capnleela** [osbridge/planning#174]
There is a list started http://stumptownsyndicate.org/wiki/Nonprofit_Fundraising_Schemes that mentions who to contact. The first week in April is when this should be done.

**Comment by capnleela** [comment]
Does anyone want to take on this task?

**Comment by akf** [comment]
I'm not sure who did this, or whether it happened, but it must be moot now, and it seems we do know where we're getting our drinks from.
