### ISSUE TITLE
choose and invite keynoters for OSBridge 2015

### ISSUE THREAD

**Issue by brainwane** [osbridge/planning#175]
Moving this from #144 since the nomination period is now over (the nomination period [closed January 31](http://opensourcebridge.org/blog/2015/01/keynote-nominations-wanted-deadline-january-31/)). I imagine the con chairs and the content committee will work on this.

**Comment by christi3k** [comment]
Here is the summary of nominations:
https://docs.google.com/spreadsheets/d/1qQ2dU16zz3SKXcdDLwxgR08UtMXAhm8tIa1bYulrXkI/edit?usp=sharing

Because I just now added the list of folks nominated via email, go ahead and add +1's to bug #144 and I'll make sure the spreadsheet is updated accordingly.

**Comment by christi3k** [comment]
Three speakers have been selected from nominations in #144 and they've been invited. Will update here when we have confirmations.

**Comment by christi3k** [comment]
All three keynotes have been confirmed.
