### ISSUE TITLE
Choose standard dates for worksprints?

### ISSUE THREAD

**Issue by shawnacscott** [osbridge/planning#177]
Since I have volunteered to make sure work sprints happen on a regular basis, I would prefer to choose standard days that they will happen in order to plan ahead most effectively.

I propose that works prints should happen first and third Saturdays from 1-5 PM. 

Thoughts?

**Comment by christi3k** [comment]
That works for me. I don't see any regular conflicts on Calagator.

**Comment by kcomandich** [comment]
Sounds great!  :+1:

**Comment by znmeb** [comment]
1st and 3rd Saturdays works for me!

**Comment by adbwl** [comment]
I have no regular conflicts, so that works for me too. 

Amanda

**Comment by akf** [comment]
It is so. I'm closing this.
