### ISSUE TITLE
Document / show Amy how to merge duplicate user accounts in OpenConferenceWare

### ISSUE THREAD

**Issue by kcomandich** [osbridge/planning#178]
@akf is going to help with this website task. It should be documented somewhere too.

This has to be done in the OCW Rails console for now. I added some code (https://github.com/osbridge/openconferenceware/pull/101) that will hopefully make this easier. @reidab needs to review first.

**Comment by akf** [comment]
I have ssh access now, so we can probably go forward with the rails console.

**Comment by reidab** [comment]
I wrote up documentation for this on the Syndicate wiki: http://stumptownsyndicate.org/wiki/Open_Source_Bridge/Technology/Combining_Duplicate_OCW_Accounts
