### ISSUE TITLE
Find speaker and attendee gifts

### ISSUE THREAD

**Issue by capnleela** [osbridge/planning#179]
We had discussed [multitools](http://www.halo.com/search.aspx?query=multitool&resultsPerPage=42) and [speakers](http://www.pinnaclepromotions.com/custom-promotional-technology-and-electronics/portable-speakers-docks-and-radios) last year as gifts. What are other ideas?

**Comment by brainwane** [comment]
I've loved the water bottles in the past. :) Brainstorming ideas:

* a teapot
* a tea infuser
* a set of velcro ties for decluttering/organizing computer cables
* a handkerchief
* a book (could be a choice/selection of a few books, e.g., The Non-Designer's Design Book by Robin Williams, The Revolution Starts At Home, Ancillary Justice, Perfecting Sound Forever)
* a deck of cards
* a set of dice where the OSB logo is the "1" side

**Comment by aeschright** [comment]
Cloth tape measures sound neat: https://twitter.com/0xabad1dea/status/570372081684066306

**Comment by akf** [comment]
I think we can close this?
