### ISSUE TITLE
Report back from Syndicate  board on using funds from December sponsorship drive

### ISSUE THREAD

**Issue by akf** [osbridge/planning#182]
(I'm adding this because I want all the action items to have a corresponding issue. Assigning one lucky Syndicate board member; please feel free to re-assign!)

**Comment by brainwane** [comment]
Hi - I'd love to know what was decided. Thank you!

**Comment by akf** [comment]
I decided Reid deserves the luck, because he's treasurer. I can tell you we're definitely using some of the funds so we can have childcare at the conference.

**Comment by brainwane** [comment]
The followup post: http://stumptownsyndicate.org/2016/04/08/what-your-support-helped-us-do-in-2015/
