### ISSUE TITLE
Check in on Stephouse and Seamless; make sure we're on their schedule and see when we need to pay them to hold the date.

### ISSUE THREAD

**Issue by akf** [osbridge/planning#193]

**Comment by christi3k** [comment]
I've emailed both Stephouse and Seamless.

**Comment by akf** [comment]
Specifically, get a quote from Seamless for video this week.

**Comment by akf** [comment]
Also ask them about backdrops in each room.

**Comment by reidab** [comment]
Calling this done, since we've emailed both of them and also heard back about video from Seamless.
