### ISSUE TITLE
research and get a quote for live captioning and or signing options

### ISSUE THREAD

**Issue by christi3k** [osbridge/planning#196]

**Comment by stenoknight** [comment]
Hi! I'd highly recommend seeking out White Coat Captioning for a quote. White Coat's captioners and I have done a ton of tech conferences between us -- SRCCon, !!Con, Strange Loop, WordCamp, PyGotham, AlterConf, and Velocity, to name a few. (And I frequently work with them, so schedule permitting I might get the chance to be your captioner.) http://whitecoatcaptioning.com

**Comment by christi3k** [comment]
Thanks for that info, @stenoknight!
