### ISSUE TITLE
Get keynoters to create stub proposals and create/update their bios

### ISSUE THREAD

**Issue by akf** [osbridge/planning#206]

**Comment by christi3k** [comment]
I emailed all three keynoters yesterday about this.

**Comment by lehudgins** [comment]
Could I get the emails for the keynoters to follow up with them and ask any questions I might have for the blog post?

**Comment by christi3k** [comment]
Kronda and Stephanie's bios should be good to go. Need to hear back from Carina.

**Comment by christi3k** [comment]
@lehudgins I've included you on emails to all three keynoters so you should be able to get in touch with the directly.
