### ISSUE TITLE
Update the sticker art with RAINBOWS

### ISSUE THREAD

**Issue by akf** [osbridge/planning#208]
It's not clear to me from our meeting notes whether "Updated sticker art with rainbows" is a thing that was done, or a desired thing. But a search for "rainbows' in this repo didn't come up with anything and now it should, so I feel that this issue is an improvement.

**Comment by reidab** [comment]
Here's one possibility for a RAINBOW-based sticker:

![osbridge_2015_square](https://cloud.githubusercontent.com/assets/13192/7905391/aefb7a5c-07cc-11e5-85fb-5a8a3fd371f6.png)

**Comment by reidab** [comment]
…and here's a mockup of a round one based on our illustration:

![osbridge_2015_round](https://cloud.githubusercontent.com/assets/13192/7905430/6c39d1ae-07cd-11e5-834c-3dad1f6116bd.png)

**Comment by akf** [comment]
:+1:

**Comment by kcomandich** [comment]
:+1:

**Comment by akf** [comment]
Everyone loves them.
