### ISSUE TITLE
Plan and create branding for podiums, behind speakers

### ISSUE THREAD

**Issue by akf** [osbridge/planning#210]
Generally, we want Open Source Bridge and Stumptown Syndicate to show up whenever someone takes a photo/video at the conference.

**Comment by akf** [comment]
Reid, I feel as if this is something you want to be involved in.

**Comment by reidab** [comment]
Spawned #245 to look at getting backdrops behind the speakers.

**Comment by akf** [comment]
I'm putting this in a milestone for next year's planning.
