### ISSUE TITLE
Hire movers for load-in & load-out

### ISSUE THREAD

**Issue by capnleela** [osbridge/planning#213]
2014: https://github.com/osbridge/planning/issues/67

**Comment by kcomandich** [comment]
Thanks to @ed-g for arranging this!
Likely we'll only need 2 hours each day.

> Ok, talked with Adam from portlands best movers. We're on their schedule.

> Estimate is $150 for the truck for each day, plus $60/hr for the two movers. He said it was around 3-4 hours last year, which I took as 3-4 hours each day. He'll bill us hourly.

> That works out to somewhere between $660 and $780.

> Also, Adam wants an XXL t-shirt!!
