### ISSUE TITLE
Get a server set up for the volunteer app

### ISSUE THREAD

**Issue by akf** [osbridge/planning#214]
Coordinate with Chris. Possibly a duplicate of #85?

**Comment by reidab** [comment]
Relevant information related to setting up uWSGI with nginx:

- [Setting up Django and your web server with uWSGI and nginx](http://uwsgi-docs.readthedocs.org/en/latest/tutorials/Django_and_nginx.html)
- [uWSGI chef cookbook](https://github.com/50onRed/uwsgi)
- [nginx + uWSGI chef cookbook](https://github.com/mattupstate/wsgi-cookbooks)

**Comment by reidab** [comment]
I think I've got things set up to run this, but need a bit more info from @ChrisFreeman before things are fully online. More info in stumpsyn/servers#31
