### ISSUE TITLE
Invite press and send passes

### ISSUE THREAD

**Issue by lehudgins** [osbridge/planning#216]
Done so far:
Invited friends who are journalists
Posted to Binders of Women Writers PDX and NW

**Comment by lehudgins** [comment]
Currently interested:
Olivia Olivia, Portland Observer
Aaron Colter, PDX Noise and Color

**Comment by lehudgins** [comment]
Andrea Janda, Vortex Magazine (Doubleclicks)
Libby Clark, Linux.com
Rick Turoczy, Silicon Florist

**Comment by lehudgins** [comment]
Malia Spencer, Portland Business Journal, mspencer(at)bizjournals(dot)com

**Comment by reidab** [comment]
Closing this out — feel free to continue press invitations.
