### ISSUE TITLE
Update schedule to reflect actual party and concert start times

### ISSUE THREAD

**Issue by akf** [osbridge/planning#221]
(TODO from 5/13 meeting)

**Comment by reidab** [comment]
@1337807 what are the official start times for the party and concert?

**Comment by 1337807** [comment]
Party starts at 6pm with the concert from 6-7 and the rest finishes at 11.

**Comment by reidab** [comment]
I've updated the online schedule with the concert and party times. We may want to tack the Open Source Citizen award presentation on to the beginning or end of the concert (probably the end).
