### ISSUE TITLE
Contact a massage therapist about providing massage

### ISSUE THREAD

**Issue by kcomandich** [osbridge/planning#222]
Jonan, would you like to contact your massage therapist friend about bringing massage to the conference again this year?

**Comment by 1337807** [comment]
Emailed Holly, the masseuse from last year. I'm not sure if she has a chair, she was the one who handled table massages in the dedicated room. If not she'll recommend someone for us.

**Comment by akf** [comment]
bump

**Comment by 1337807** [comment]
We have a massage therapist! She hasn't confirmed hours yet but she will be there at least 2 days in the hacker lounge.

**Comment by kcomandich** [comment]
Charise Caldwell will be our massage therapist:
> I'm planning on being at OSB from 3:00-5:30 on the 24th and 12:00-7:00 on the 25th. =)
