### ISSUE TITLE
Determine where movers are to move things back to (storage unit with better access hours)

### ISSUE THREAD

**Issue by akf** [osbridge/planning#223]

**Comment by reidab** [comment]
Here's the storage unit comparison I mentioned having put together when I was moving: https://docs.google.com/spreadsheets/d/1ubiJpLBLeMVa9EfbKXvu1-g1AP_UtwAtr9L5ZX6-HhU/edit?usp=sharing

**Comment by kcomandich** [comment]
Of the ones on Reid's spreadsheet, I've narrowed it down to:
* Central Self Storage, 1323 NW 16th Ave
 * I paid $20 online to reserve a 9 x 14.5 for $229/mo
 * (was this the one Kurt said the policies were weird?)
* South Waterfront Heated Storage, 0680 SW Bancroft Street
 * filled in their form, waiting to hear back
* Yeon Mini Storage, 3055 NW Yeon Ave 
 * will have to call Monday to check availability

All the other ones either have no availability in the size we need (10x15) or their access hours are no better than our current unit.

**Comment by neophiliac** [comment]
Central Self Storage sent some mailings shortly after they opened with spelling and grammar that a 5th-grader would be ashamed of. That's is the entirety of what I know about them. 

I would not let that stop you from storing stuff in their facility if their features fit your needs. Spelling and grammar are not super relevant to the operation of a storage business.

**Comment by kcomandich** [comment]
Thanks Kurt, I had forgotten that that was what you'd said.

Update, we're down to two options:
* Yeon Mini Storage does have a 10x15 available, $218
* Central Self Storage, 9 x 14.5 for $229

I will try to visit them both tomorrow.

* South Waterfront does not have one available.

**Comment by kcomandich** [comment]
Rented!
https://www.yeonministorage.com/
3055 NW Yeon Ave
access hours: 6am-9pm daily

<em>(Central Self Storage had a booking right before mine that meant there were no more available in our size. They were very helpful at trying to find alternatives but Yeon turned out to be a better option.)</em>
