### ISSUE TITLE
Check what kind of radios do we have and whether there are headsets with them.

### ISSUE THREAD

**Issue by akf** [osbridge/planning#229]
If no headsets, order some from Amazon.

**Comment by kcomandich** [comment]
They are six Motorola SX600R two-way radios and chargers.
http://stumptownsyndicate.org/wiki/File:Motorola_Radios.jpg

We have no headsets. Can someone order some?

**Comment by neophiliac** [comment]
Over-ear (http://www.amazon.com/Motorola-53725-Headset-Swivel-Black/dp/B00000JCT8), dangly-bit (http://www.ebay.com/itm/High-Quality-Headset-Earpiece-for-Motorola-Radio-MR560-SX600R-T5030R-US-STOCK-/180700390831) or secret service (https://www.planetheadset.com/Motorola/SX600.php, first one on the page)?

I have used the secret service type with a throat mic, and they work really well. The dangly-bit ones are cheapest, as low as $4. I think the over-ear will make people with radios stand out so people know who to ask for help. And they're a little more sanitary for sharing.

**Comment by kcomandich** [comment]
We might also need to buy new batteries for them. I've had them charging for 24+ hrs now and they aren't turning on. (Instructions say to charge for 14 hours).

Let's decide at/by this Wednesday's meeting what we need to buy.

**Comment by ed-g** [comment]
I have two additional AA-powered GMRS radios I'd be happy to loan to 
OSBridge.

Ed

**Comment by kcomandich** [comment]
We decided at the meeting tonight that we will arrange to get actual radios from Seamless instead of using our own.
