### ISSUE TITLE
Arrange Costco run with Kurt

### ISSUE THREAD

**Issue by akf** [osbridge/planning#233]
@neophiliac 

Not sure who committed to doing this; guessing it's @reidab or that he knows.

**Comment by kcomandich** [comment]
I will get Kurt a shopping list from last year.

**Comment by 1337807** [comment]
Add snacks and drinks for children to the list please, we have childcare! :)

**Comment by kcomandich** [comment]
Are we cutting some of this due to budget?

Here are the shopping lists from Costco:
https://www.dropbox.com/sh/isxbpr6ohgzof4f/AABl8hH6GI515gkNnbeL-vk1a?dl=0
and Trader Joe's last year:
https://www.dropbox.com/sh/4071ud1ie2vz2q8/AABIvsJTyZYWG9UmiATLkkDta?dl=0
with some photos for reference.

**Comment by reidab** [comment]
I'm guessing that our Costco and Trader Joe's snacks are some of the more cost-efficient things that we buy. Let's look at it all this evening and see where we stand.

**Comment by neophiliac** [comment]
Are we changing quantities and/or dropping anything on these lists, and are there suggestions for kid-specific snacks? I can choose things that kids will like and caretakers won't hate (e.g. fruit leather good, ice cream bad), but it would be good to have a theme for anything not on the list to prevent wasted time in the store.

**Comment by reidab** [comment]
I'm reviewing this now.

**Comment by reidab** [comment]
I've searched Costco's catalog and copied over better descriptions for last year's items to this spreadsheet: https://docs.google.com/spreadsheets/d/1swyR3-fpaEX5dHRevXC9FOwL8IQt3Xp09nE1YnLJKmI/edit#gid=0

I've added a small amount of extra dried fruits and nuts for possible oatmeal additions, and cut the wine in half.

This doesn't currently include anything specifically for kids snacks, though there's definitely some crossover.

**Comment by neophiliac** [comment]
Got it I will begin the shopping adventure soon. DM @neophiliac, Gchat ratbelt@gmail.com, or call 503 869 3581 with last-minute changes.
