### ISSUE TITLE
Organize party catering

### ISSUE THREAD

**Issue by akf** [osbridge/planning#235]

**Comment by akf** [comment]
@capnleela, I think you're doing this? I'm just checking through unassigned tickets and finding them people.

**Comment by capnleela** [comment]
I updated the order in this spreadsheet https://docs.google.com/spreadsheets/d/1hh7ORFmCB1ixbSdieh4ObO2iKVndwi6Odzd08YGlL0s/edit#gid=17 under the "party" tab

**Comment by reidab** [comment]
Party catering has been ordered! Thanks @capnleela!

I've paid a deposit for the Pambiche order and have paid Back to Eden in full.
