### ISSUE TITLE
Organize doughnut truck

### ISSUE THREAD

**Issue by akf** [osbridge/planning#236]

**Comment by ed-g** [comment]
When do we want the donut truck? Friday morning?

**Comment by reidab** [comment]
Aye, Friday morning. I think we usually do it from about 8–10, but I'd confirm with past years.

**Comment by capnleela** [comment]
Ed, this was in that email thread from last year that I forwarded you. Truck last year was booked for 8:30 to 9:30am. Thanks!

**Comment by ed-g** [comment]
@capnleela oops it was, and I missed it!

**Comment by ed-g** [comment]
Budget check for this.

**Comment by ed-g** [comment]
Call and see how much notice Voodoo needs for donut truck.

**Comment by ed-g** [comment]
Probably won't order them due to budget. If necessary we will call and ask if/when funds show up.

**Comment by ed-g** [comment]
Will call Thursday to see what their lead time is. Contact.


Nathan Banfi
Voodoo Doughnut Mobile Coordinator
Email: voodoovan@voodoodoughnut.com
Cell: (503) 548-8443
FB: Voodoo Doughnut Mobile

**Comment by ed-g** [comment]
I've emailed to see what lead they need.

**Comment by reidab** [comment]
@ed-g If they get back to you and are still bookable, it's looking like we may have budget for this.

**Comment by reidab** [comment]
@ed-g did we get this confirmed?

**Comment by ed-g** [comment]
Truck is booked for Friday. Instead we are picking up 16 dozen from voodoo two on sandy, at 7:30am Friday. We need to pay 24 or more hours in advance.

**Comment by capnleela** [comment]
Are they emailing over an invoice? And is dropping off a check ok? They are cash only, so I don't think the cash card will work for this.

**Comment by ed-g** [comment]
They should be emailing paypal invoice although I haven't gotten it yet. Otherwise we can give them cash. In either case 24 hours before pickup. Total $235.20.

**Comment by ed-g** [comment]
No checks.

**Comment by ed-g** [comment]
I'll call voodoo too again Wednesday if I don't get an email by then.

**Comment by ed-g** [comment]
Paypal invoice here.

https://www.paypal.com/us/cgi_bin/webscr?cmd=_pay-inv&id=INV2-VVHB-HAFE-XLZF-62PV
