### ISSUE TITLE
Find out whether O'Reilly will send us books to raffle

### ISSUE THREAD

**Issue by akf** [osbridge/planning#243]
And if so, put together a request.

**Comment by neophiliac** [comment]
The person to ask is Jason Yee (Community Manager, O'Reilly Media, Inc.). He's in Portland. I haven't found an email for him yet, but maybe a call to O'Reilly will get his voicemail box?

**Comment by capnleela** [comment]
I have his contact info from meeting him recently. Will reach out.

**Comment by 1337807** [comment]
Reached out to Betsy today, we'll get there somehow.

**Comment by akf** [comment]
Multiple contacts have come up with nothing. Obviously if we hear otherwise we'll ask for books, but we don't need this issue anymore.
