### ISSUE TITLE
Design and Order Scout Books for attendee gifts

### ISSUE THREAD

**Issue by reidab** [osbridge/planning#244]
We'd like to order Scout Books for attendee notebooks. The cost for these is $695.00 for 500 books, or $1.39 per notebook.

I've designed a cover based on Taylor's illustrator work for review:

![2015-cover-preview](https://cloud.githubusercontent.com/assets/13192/7893927/e95141ca-0617-11e5-8727-cb4c90799ecc.png)

In the same ink as last year's books:
<a href="https://www.flickr.com/photos/reidab/15222007889" title="Open Source Bridge 2014 by Reid Beels, on Flickr"><img src="https://c1.staticflickr.com/3/2944/15222007889_e3704d58d6_z.jpg" width="640" height="424" alt="Open Source Bridge 2014"></a>

**Comment by akf** [comment]
:+1:

**Comment by kcomandich** [comment]
:+1:

**Comment by reidab** [comment]
I tried to place the order online and got a payment form error, so I've emailed them the artwork and asked to confirm that they can have things done by the conference. Once I hear back from them, I'll try their form again.

**Comment by akf** [comment]
Yesterday you reported these as ordered, so closing (and yay).
