### ISSUE TITLE
Decide on party ticket price, if any, for OSB attendee guests

### ISSUE THREAD

**Issue by kcomandich** [osbridge/planning#247]
Since we have fabulous party plans, people will want to bring friends.

Previous ticket prices (free, $10, $20 for OMSI):
http://stumptownsyndicate.org/wiki/Open_Source_Bridge/Registration/Historical_Ticket_Prices

**Comment by akf** [comment]
Done, right?

**Comment by kcomandich** [comment]
Yes, thanks Amy. We decided on a sliding-scale ticket.
We will not be able to collect money at the door, since we are using volunteer alcohol servers (OLCC rules).
