### ISSUE TITLE
Figure out if we have enough lanyards & if I need to order more.

### ISSUE THREAD

**Issue by kcomandich** [osbridge/planning#248]
See #92 for info from last year.

**Comment by kcomandich** [comment]
Current stock: 558 Syndicate lanyards: 228 blue, 158 yellow, 172 red.
We started OS Bridge 2014 with 503 blue, 200 yellow, and 200 red.

Looks like we need to order some more blue ones.

**Comment by reidab** [comment]
I remember you saying you ordered these :+1: 

Closing

**Comment by kcomandich** [comment]
Yes, ordered 500 navy. I just reviewed & accepted the proof.
