### ISSUE TITLE
Schedule a walkthrough for joey@confreaks.com

### ISSUE THREAD

**Issue by akf** [osbridge/planning#252]

**Comment by ed-g** [comment]
Before conference any time, schedule with Holi as well.

**Comment by ed-g** [comment]
contacted Joey.

**Comment by ed-g** [comment]
Joey is available June 11th through 13th, or June 21st. He said walk through would be nice but not absolutely necessary. Holi is out of town. Do we have any other contact for scheduling walkthrough of Eliot center?

**Comment by ed-g** [comment]
No response from Holi. I've asked about a last minute walk through Sunday.

**Comment by ed-g** [comment]
May happen some time sunday.

**Comment by ed-g** [comment]
Not happening, Joey and Holli's schedules do not mesh.
