### ISSUE TITLE
Place ad for runner

### ISSUE THREAD

**Issue by ed-g** [osbridge/planning#253]

**Comment by ed-g** [comment]
Make sure to get copy of their drivers license and car insurance card.

**Comment by ed-g** [comment]
Check references

**Comment by ed-g** [comment]
Have tentative yes, will know Thursday 11th.

**Comment by ed-g** [comment]
We have confirmed, Rickey Chewning, 682-597-8233.

How do we handle providing him a downtown parking pass?

**Comment by kcomandich** [comment]
Last year we had Vincent provide his parking receipts, and we reimbursed him.

**Comment by ed-g** [comment]
Perfect thanks Kirsten
