### ISSUE TITLE
Add to runner list: pick up games from Guardian games Thursday

### ISSUE THREAD

**Issue by ed-g** [osbridge/planning#257]
Questions:

What is Guardian Games address, and phone number?

Do we need to have them contact a specific person there?

**Comment by ed-g** [comment]
I've found the address on the Internet. Do we need to give them money or are these donations?

**Comment by akf** [comment]
It's a sponsorship; we don't need to give them money. If I recall correctly, the games will be on loan to us. Probably a good idea to call and give them a heads-up to expect the runner at a certain time anyway.

**Comment by akf** [comment]
I just remembered -- there's information in the sponsorship spreadsheet about this: 

"Send runner to pick up games (21): For Sale, Settlers of Catan, SmallWorld, 7 Wonders, Dominion, Ticket to Ride, Alhambra Big Box, Settlers of America, Fluxx Citadels, Mage Wars, Smash Up, Munchkin Deluxe, Magestorm, Bananagrams, Dixit, Cthulhu Gloom, Telestrations, Takenoko, Wits & Wagers, Carcassonne"

It doesn't list a specific contact name. Jonan is the one who talked to them, but I think they'll know who we are.

**Comment by ed-g** [comment]
We will pick up 2pm Thursday. Need to return by their end of day Thusrday, or when they open which is 10am Friday. Jonan call to verify list of games..

**Comment by ed-g** [comment]
Ok I'll call them back and give them the list. Jonan you won't need to call.

**Comment by ed-g** [comment]
No answer to call, sent email to info@ggportland.com
