### ISSUE TITLE
Send Daily Newsletter: Wednesday Edition

### ISSUE THREAD

**Issue by reidab** [osbridge/planning#266]
We send a daily newsletter to attendees each day of the conference. This is sent via Eventbrite.

1. Review [last year's newsletter outline and the archive of sent newsletters](http://stumptownsyndicate.org/wiki/Open_Source_Bridge/2014/DailyNewsletter)
2. Write a new message in [this Etherpad](http://etherpad.stumptownsyndicate.org/p/osb15-wednesday-newsletter)
3. Send via Eventbrite

**Comment by capnleela** [comment]
For Wednesday, we will have: Fruit, nuts, and Organic Steel-Cut Oatmeal from Pacific Foods http://www.pacificfoods.com, lunch by the Ethiopian restaurant Bete-Lukas http://bete-lukas.com/, cookies for the afternoon break from Sweetpea Baking http://sweetpeabaking.com/ and Petunia's Pies and Pastries http://petuniaspiesandpastries.com/.

**Comment by reidab** [comment]
Please plug the citizenship award sign-up sheet and BoF sign-ups on the board in the hacker lounge.

**Comment by lehudgins** [comment]
Any schedule changes?
-Lauren

**Comment by reidab** [comment]
http://opensourcebridge.org/sessions/1624 is either cancelled or changing speakers, but we sadly don't know which one yet…

**Comment by lehudgins** [comment]
We still have availability for childcare, right?

**Comment by reidab** [comment]
Yes
