### ISSUE TITLE
Send Daily Newsletter: Thursday Edition

### ISSUE THREAD

**Issue by reidab** [osbridge/planning#267]
We send a daily newsletter to attendees each day of the conference. This is sent via Eventbrite.

1. Review [last year's newsletter outline and the archive of sent newsletters](http://stumptownsyndicate.org/wiki/Open_Source_Bridge/2014/DailyNewsletter)
2. Write a new message in [this Etherpad](http://etherpad.stumptownsyndicate.org/p/osb15-thursday-newsletter)
3. Send via Eventbrite

**Comment by reidab** [comment]
This talk was cancelled this morning, but is now back on for tomorrow afternoon with an alternate speaker: http://opensourcebridge.org/sessions/1624

Dana was stuck in PHL, so Matthew will be presenting in her stead. Dana may Skype in to answer questions.

**Comment by capnleela** [comment]
For Thursday's food: Fresh and dried fruit and nuts, oatmeal from Pacific Foods http://www.pacificfoods.com/, lunch is catered by Thai Garden http://www.yelp.com/biz/thai-garden-portland, cookies by Sweetpea Baking http://sweetpeabaking.com/ and Petunia's Pies & Pastries http://petuniaspiesandpastries.com/ (gf). Party food catered by Pambiche http://pambiche.com/, with dessert by Back to Eden Bakery http://backtoedenbakery.com/.
