### ISSUE TITLE
Pick up gift card for errand runner to use

### ISSUE THREAD

**Issue by kcomandich** [osbridge/planning#273]
probably at Safeway when other things are picked up

**Comment by reidab** [comment]
Last year we got a $500 card. The errand runner may have fewer direct payments this year. Reid to review and get appropriately-sized card.

**Comment by kcomandich** [comment]
Here is the list of purchases from last year:


![osb 2014 errand runner purchases](https://cloud.githubusercontent.com/assets/12370/8262825/53537066-168a-11e5-9888-64f84819a609.png)

**Comment by reidab** [comment]
Thanks! That confirms my suspicions that a lot of last year's expenses were the one-time purchases at Rose's.
