### ISSUE TITLE
Wiki error uploading an image

### ISSUE THREAD

**Issue by akf** [osbridge/planning#278]
I tried to upload photos of the unconference board to the wiki and got an error like this: 

Internal error

[0b60d3cb] /wiki/Special:Upload Exception from line 1871 of /var/www/mediawiki/includes/filerepo/file/LocalFile.php: Could not acquire lock for '2015unconference-1.jpg.'

Backtrace:

#0 /var/www/mediawiki/includes/filerepo/file/LocalFile.php(1174): LocalFile->lock()
#1 /var/www/mediawiki/includes/upload/UploadBase.php(738): LocalFile->upload(string, string, string, integer, array, boolean, User)
#2 /var/www/mediawiki/includes/upload/UploadFromUrl.php(356): UploadBase->performUpload(string, string, boolean, User)
#3 /var/www/mediawiki/includes/specials/SpecialUpload.php(467): UploadFromUrl->performUpload(string, string, boolean, User)
#4 /var/www/mediawiki/includes/specials/SpecialUpload.php(186): SpecialUpload->processUpload()
#5 /var/www/mediawiki/includes/specialpage/SpecialPage.php(363): SpecialUpload->execute(NULL)
#6 /var/www/mediawiki/includes/specialpage/SpecialPageFactory.php(584): SpecialPage->run(NULL)
#7 /var/www/mediawiki/includes/MediaWiki.php(275): SpecialPageFactory::executePath(Title, RequestContext)
#8 /var/www/mediawiki/includes/MediaWiki.php(584): MediaWiki->performRequest()
#9 /var/www/mediawiki/includes/MediaWiki.php(435): MediaWiki->main()
#10 /var/www/mediawiki/index.php(46): MediaWiki->run()
#11 {main}

**Comment by reidab** [comment]
Fixed! There was a permissions issue with the lockdir.
