### ISSUE TITLE
Open up 2016 CFP

### ISSUE THREAD

**Issue by swenson** [osbridge/planning#286]
Some more details are present at http://stumptownsyndicate.org/wiki/Open_Source_Bridge/Technology/Website_Updates_for_Opening_Proposals

- [x] Wordpress title bar
- [x] Dates at top right under "The conference for open source citizens" in OpenConferenceWare
- [x] Dates at top right under "The conference for open source citizens" in Wordpress: Update the shared fragment files on Arroway at /var/www/osbridge-ocw/shared/public/system/shared_fragments/header_*. 
- [x] Update symlink to point to 2016 header
- [x] Lanyrd link in left sidebar: Update Wordpress: Appearance > Widgets > Frontpage sidebar
- [ ] Sponsors on homepage: Update Wordpress: Appearance > Widgets > Sponsors sidebar
- [x] Eventbrite should already be set up.
- [x] Make sure the osbugluv and osbhtml discount codes are created
- [x] Create badges for the new year in https://github.com/osbridge/osbp_assets
- [x] Upload badges to Arroway: /var/www/badges/$NEW_YEAR/
- [x] Edit WordPress page for http://opensourcebridge.org/get-involved/promote/. IMPORTANT: DO NOT use the default WordPress "Visual" editor because it destroys formatting and escaping, please use the "HTML" editor instead. The easiest way to update the HTML is to copy the markup into a text editor, and use its search-and-replace to update the (1) year, (2) month/day, and anything else. Create a local HTML file using the badge's HTML and confirm that it's okay.
- [x] Update http://opensourcebridge.org/sponsors/sponsor-resources/ using a similar approach to the above.
- [x] Update OpenConferenceWare by editing app/views/open_conference_ware/proposals/create.html.erb in https://github.com/osbridge/open-source-bridge-proposals. Redeploy
- [x] Update http://opensourcebridge.org/media
- [x] Update http://opensourcebridge.org/attend
- [x] Update http://opensourcebridge.org/call-for-proposals
- [x] Update http://opensourcebridge.org/get-involved/for-user-groups
- [x] Update http://opensourcebridge.org/get-involved/promote
- [x] Update http://opensourcebridge.org/sponsor-resources
- [ ] Update http://opensourcebridge.org/sponsors/sponsorship
- [x] Create this page in Wordpress: http://opensourcebridge.org/y$NEW_YEAR (note the y before the year). Copy the content from a previous year.
- [x] Create this page in Wordpress: http://opensourcebridge.org/sponsors/y$NEW_YEAR (note the y before the year).
- [x] Update the ^/sponsors/?$ redirection to /sponsors/y$NEW_YEAR/ in Wordpress's redirection tool
- [x] Update  http://opensourcebridge.org/ The main content of this page has several year-specific links. Edit the content of the page "FrontPage" in WordPress to update it.
- [x] Create http://opensourcebridge.org/wiki/$NEW_YEAR/Main_Page
- [x] Link to it from http://opensourcebridge.org/wiki/Main_Page
- [ ] There are probably other places in the wiki that need to be re-verified for the new year
- [x] Update http://opensourcebridge.org/about (after the new event is created in OCW)
- [x] Add Tracks
- [x] Add Session Types
- [x] Set dates for Event
- [ ] set proposal deadline to the past if not opening just quite yet.
- [x] Create BoF (Birds of a Feather) Event
- [x] Add BoF Track
- [x] Add BoF Session Type
- [x] Set the current event for OCW: Update config.current_event_slug in config/initializers/01_open_conference_ware.rb in https://github.com/osbridge/open-source-bridge-proposals. Redeploy.
- [x] Ensure CFP is open in OpenConferenceWare

**Comment by shawnacscott** [comment]
* Eventbrite is set up at https://www.eventbrite.com/e/open-source-bridge-2016-registration-22759978709
* osbugluv and osbhtml discount codes are live
* The Lanyrd link still needs to be added to the sidebar, but it's live at http://lanyrd.com/2016/osb16/

I'll look through the wiki and see what I can find that needs updating.

@thursdayb should have sponsorship info soon. I believe the prospectus is just getting one final polish.

**Comment by kcomandich** [comment]
You can use https://osbridge.eventbrite.com/ now too. It redirects to the original URL.

**Comment by shawnacscott** [comment]
[ ] Check that Hootsuite is set up to auto update with new CFP proposals

**Comment by ed-g** [comment]
Added lanyrd link and /sponsors redirect.
