### ISSUE TITLE
Web site: "About" sidebar needs an update

### ISSUE THREAD

**Issue by akf** [osbridge/planning#287]
If I knew, I don't recall how the "About" sidebar is generated. In any case, it deserves a review. 

Go to http://opensourcebridge.org/about/

Note that "2014 Conference Team" is prominent in the sidebar. There is a "2016 Conference Team" page that should take its place. The 2014 page is at /about/our-team and 2016 is at /conference-team

**Comment by reidab** [comment]
This sidebar definitely comes from WordPress. It's either the default sidebar and is coming through because no widgets have been added to it, or it's a page list widget. Either way, we should be able to trim things down.

**Comment by akf** [comment]
Hi Reid, thanks! I'll bet it's the default sidebar. I've found my way into the "Customize" view that tells me that "no widgets are rendered" on the About page.

**Comment by gabelula** [comment]
- [ ] Make a list of what needs to be in the sidebar
- [ ] Change it

**Comment by thursdayb** [comment]
About
Call for Proposals 2018
Sponsorship 2018
Code of Conduct
Get Involved
Contact Us
