### ISSUE TITLE
Content

### ISSUE THREAD

**Issue by meli-lewis** [osbridge/planning#291]
# Prep for Talk Selection
- [x] Open CFP
- [x] Create keynote speaker nomination form
- [x] Promote CFP
- [x] Blog posts about CFP
- [x] Organize speaker support office hours
- [x] Host brainstorming hangouts
- [x] Pick date for content selection meeting
- [x] Find venue for content selection meeting
- [x] Make and prioritize list of potential content reviewers
- [x] Contact prioritized list of content reviewers until we have 10-15 reviewers
- [x] Give content reviewers admin access
- [x] Provide content reviewers with details about location timing for content selection meeting.
- [x] Remind reviewers about talk selection and meeting.
- [x] Get list of rooms, time slots, etc. to verify timing for talk selection
- [ ] Make list of non-talk activities
- [ ] Prepare spreadsheet for talk selection meeting.
- [ ] Prepare materials to facilitate talk selection meeting.
- [x] Organize snacks for talk selection meeting.
# Talk Selection and Scheduling
- [x] Host talk selection meeting and select talks
- [x] Contact accepted speakers
- [x] Contact keynotes
- [x] Contact waitlist speakers
- [x] Contact backup keynotes, if needed
- [x] Determine talk schedule
- [x] Verify talk schedule with speakers
- [x] Publish talk schedule
# Prep for conference
- [ ] Preconference email with information about conference
- [ ] Contact talk selection volunteers about free tickets
- [ ] Get volunteers for greenroom during conference
- [ ] Get volunteers for speaker support during conference
- [ ] Pre-conference speaker support
- [ ] Preparation of immigration letters for non-US speakers.
- [ ] Check in with speakers and make sure we have contact and travel details for everyone.
- [ ] Print checks for keynote honorariums.
- [ ] Collect intro songs for keynote speakers and send them to organist.
- [ ] Create session runner cards
- [ ] Send list of content volunteers to person creating the program
- [ ] Send schedule to person creating the program
- [ ] Facilitate requests for travel assistance

**Comment by shawnacscott** [comment]
There's also a discount code for user groups that you can include in any outreach, and there is also a meta user group google group that we should notify as well. :)

**Comment by meli-lewis** [comment]
Do I parse that correctly as saying there's a google group for people who organize meetups?!

**Comment by shawnacscott** [comment]
You do indeed! pdxgroups@googlegroups.com.
