### ISSUE TITLE
Suggestions for 2017

### ISSUE THREAD

**Issue by thursdayb** [osbridge/planning#292]
- [ ] FAQ for speakers about security / way for prospective speakers to tell us about needs for increased security (#313)

**Comment by shawnacscott** [comment]
-[ ] Fix the OCW profile merge problem

**Comment by swenson** [comment]
[ ] In selector votes, also have (optional) display of how you voted and what you said.

**Comment by swenson** [comment]
- [ ] add a view for what I gave 5s to

**Comment by aeschright** [comment]
[ ] order floor decals with the conference logo (Sticker Mule has started offering these, $49 each)

**Comment by shawnacscott** [comment]
Wish list for OCW:
- [ ] management portal for committee chairs to: 
  - [ ] submit items they need purchased
  - [ ] contracts to sign
  - [ ] w9s received? (tricky b/c privacy)
  - [ ] upcoming vendor contracts
  - [ ] generate  signs / forms
    - [ ] session monitor cards
    - [ ] incident response forms
    - [ ] door cards with all talks in that room for each day
    - [ ] directional signs
    - [ ] etc.    

- [ ] aggregate reports for co-chairs
  - [ ] current total ticket sales, compared to year over year
  - [ ] sponsor fulfillment

Venue things:
- [ ] box fans for A-side speaker, staff, volunteer, and media lounges (some have no air)
- [ ] scheduled hacker lounge demos with fun things (zine making, solder, etc.) (maybe a maker track?)

Organizer things:
- [ ] mandatory staff briefing for all staff ahead of time
  - [ ] include that people can go home if not well. We can cover it.

More to come! 🎉

**Comment by paigetech** [comment]
* [] Print out Volunteer roles
* [] Add speaker gifts to session monitor role and Session Sheets
* [] Walkie Talkies from seamless (or batteries AAA for ours)

**Comment by paigetech** [comment]
* [ ] figure out font situation with OCW

**Comment by elea** [comment]
- [ ] Make at least the schedule page mobile-friendly

**Comment by azurelunatic** [comment]
- [ ] When possible, include speaker names on the mini schedule in the badge. 

(There may not always be room, but I've missed things I'd planned to see due to not remembering all my acquaintances' talk titles.)

**Comment by azurelunatic** [comment]
- [ ] Blue tape clearance zones around room entrances as well as in the hacker lounge. 

- [ ] Index the tea more visibly (record store type label cards) 

- [ ]  Those flimsy plastic folding chairs from Able Party Rental are only suitable for the smaller attendees, and creates an unequal seating situation.

**Comment by christi3k** [comment]
- [ ] add ticketing and registration features

**Comment by reidab** [comment]
Checking things off on this list as they get mentioned or worked in to 2017 planning issues.

**Comment by reidab** [comment]
@paigetech Can you tell me more about what you were thinking around this?

>  Codify "Open Source Lunch" for ideas/volunteer interaction
— https://github.com/osbridge/planning/issues/292#issuecomment-227615896

**Comment by reidab** [comment]
@paigetech also, what was the OCW font situation mentioned in https://github.com/osbridge/planning/issues/292#issuecomment-227775575?
