### ISSUE TITLE
update "See this talk at Open Source Bridge 2015!" to 2016

### ISSUE THREAD

**Issue by brainwane** [osbridge/planning#297]
![see-in-2015](https://cloud.githubusercontent.com/assets/842790/15258554/3db3b7a0-191a-11e6-9e59-7d4a37c1f5e5.png)

This is a screenshot of http://opensourcebridge.org/sessions/1906 - it says "See this talk at Open Source Bridge 2015!" but should instead mention 2016, the current year.

**Comment by kcomandich** [comment]
Thanks for letting us know Sumana! It's fixed now.

**Comment by reidab** [comment]
I was about to make a version of this task to update it again for this year, but I see you made it pull the year dynamically from the proposal. Thanks @kcomandich!

**Comment by kcomandich** [comment]
🎉
