### ISSUE TITLE
Collect Elliot Center Use Ideas/Changes

### ISSUE THREAD

**Issue by paigetech** [osbridge/planning#299]
We need to collect the proposed changes in how we are going to be using the venue this year.

Thus far, I have:
- not using the basement hall to serve food (because we're not serving food)
- may use kitchen for snacks, but may not
- using more A side classrooms than last year? (they are officially on the contract this year)

What am I missing?

**Comment by capnleela** [comment]
Child care room will need to be moved from the basement hall adjacent area to a spot closer to the conference. Possibly one of those A side rooms?

-Melissa
