### ISSUE TITLE
🚐 Find information about parking for food carts

### ISSUE THREAD

**Issue by arielspear** [osbridge/planning#302]
find out city information about reserving street parking

**Comment by reidab** [comment]
We're looking into this for 2017 as well. @arielspear said she talked to the city last year and they would issue street parking permits for parking, but not for food truck vending. Investigating the parking lots across from and around the Eliot center.

**Comment by reidab** [comment]
All the nearby lots seem to be run by [City Center Parking](http://citycenterparking.com), even though some of them are branded as "U-Park". 

In order of preference, these lots are the closest:

1. Across Salmon from Eliot Center: Lot 348
2. Across 12th from Sanctuary: Lot 91 + Lot 189
3. SW 11th and Salmon: Lot 20
4. SW 12th and Taylor: Lot 22 + Lot 13
