### ISSUE TITLE
🚛 2017 OSB Supply Shopping List

### ISSUE THREAD

**Issue by reidab** [osbridge/planning#308]
Add items here that we need to purchase before the 2017 conference. See #300 for some 2016 info.

**Comment by elea** [comment]
We need some outside signage to indicate the entrance of Open Source Bridge. Last year, disabled folks mentioned particularly having issues finding the entrance (we just did chalk on the sidewalk, which didn't work very well). I recommend having an A-sign and perhaps getting some local company to donate one for us?

**Comment by gabelula** [comment]
Add stuff to this ticket if you think it should be in the list.

**Comment by thursdayb** [comment]
Febreeze

**Comment by aeschright** [comment]
Dollar store glow sticks for the party

**Comment by reidab** [comment]
Sidewalk chalk

**Comment by reidab** [comment]
Glue sticks

**Comment by reidab** [comment]
Face paint

**Comment by reidab** [comment]
Plastic tablecloths

**Comment by thursdayb** [comment]
For face paint: https://smile.amazon.com/Dress-Up-America-Vibrant-Non-Toxic/dp/B01N1FD6YI/ref=sr_1_14?ie=UTF8&qid=1497495814&sr=8-14&keywords=face+paint

**Comment by reidab** [comment]
Ordering from Amazon:
- gaffers tape
- blue tape
- plastic tablecloths
- face paint crayons
- glue sticks
- volunteer labeling stickers
