### ISSUE TITLE
Ask Aaron about keynote video recording/streaming

### ISSUE THREAD

**Issue by reidab** [osbridge/planning#317]
We've heard good things about the video streaming work @aaronpk has been doing around town lately for donuts.js and other events. We'd like to see if he'd be interested in doing this for our three morning keynotes this year. Let's contact him and ask (unless mentioning him in this issue ends up being enough to do that 😄).

**Comment by aaronpk** [comment]
Hi! I would have loved to, but unfortunately I'm going to be out of the country for most of osbridge! I'm coming back Wednesday night the 21st. 😞

**Comment by reidab** [comment]
Thanks! That's a shame. Hope to see you for the last few days.
