### ISSUE TITLE
💁🏽 Announce and promote keynote speakers

### ISSUE THREAD

**Issue by reidab** [osbridge/planning#318]
* [x] Get photos and bios from keynoters
* [x] Add keynotes to OCW and schedule
* [x] Schedule tweets about each keynote
* [x] Send email announcing keynotes
* [x] Create blog post announcing keynotes
* [x] Share blog post on Facebook about keynotes

**Comment by reidab** [comment]
Blog post is finally loaded into wordpress and scheduled to publish tomorrow — working on adapting it to an email as well.

**Comment by elea** [comment]
Done
