### ISSUE TITLE
🔰 Acquire Stickers

### ISSUE THREAD

**Issue by reidab** [osbridge/planning#322]
* [ ] Decide what stickers to print
* [ ] Design stickers
* [ ] Choose sticker vendor
* [ ] Order stickers
* [ ] Receive stickers
* [ ] Stick first sticker on a thing

**Comment by reidab** [comment]
From the 2016 feedback, there's a suggestion to look into floor decals with conference branding: https://github.com/osbridge/planning/issues/292#issuecomment-227539450

**Comment by thursdayb** [comment]
We have about 100 of the following: 
light blue Open Source Bridge 
white Open Source Bridge

We have 50 or fewer of the following: 
rainbow Open Source Bridge
dark blue Open Source Bridge
Stumptown Syndicate
Intersectional Feminism Fuck Yeah
Open Source Fuck Yeah

I would consider **the rainbow Open Source Bridge and Stumptown Syndicate stickers** to be a priority, followed by **Open Source and Intersectional Feminism Fuck Yeah stickers**
