### ISSUE TITLE
🌬 Ensure sufficient air flow / cooling in A-side classrooms

### ISSUE THREAD

**Issue by reidab** [osbridge/planning#325]
From 2016 post-conf feedback (https://github.com/osbridge/planning/issues/292#issuecomment-227598324)

Some classrooms on the A side of the Eliot center building have no AC and very little air flow. We may want to acquire some box fans to lessen suffering to the staff and volunteers using these rooms.

**Comment by elea** [comment]
This was confirmed onsite
