### ISSUE TITLE
📛 Print attendee badges

### ISSUE THREAD

**Issue by reidab** [osbridge/planning#329]
* [x] Decide whether to keep the same format for program/badges this year
* [ ] Design badges
* [ ] Order badges

**Comment by reidab** [comment]
From the 2016 feedback: 
> When possible, include speaker names on the mini schedule in the badge.

**Comment by gabelula** [comment]
Related to https://github.com/osbridge/planning/issues/340

**Comment by elea** [comment]
Updating this task as we now are printing badges only and not programs
