### ISSUE TITLE
⛑ CoC and Incident Response training

### ISSUE THREAD

**Issue by reidab** [osbridge/planning#333]
Based on last year's incident response issue (#301), we'll need to:

* [x] train volunteer coordinators on plans and expectations
* [x] train primary responders on plans and expectations
* [x] train volunteers on-site about CoC and incident response expectations

**Comment by thursdayb** [comment]
Volunteer training on Monday June 19
Sara + Thursday — co-lead responders

**Comment by aeschright** [comment]
We're going to do a short refresher for the response team on 6/14 and make sure all documents are up to date.
