### ISSUE TITLE
👶 Arrange Childcare

### ISSUE THREAD

**Issue by reidab** [osbridge/planning#335]
* [ ] Review childcare registration numbers
* [x] Research childcare providers
* [x] Choose childcare provider
* [ ] Care for children

**Comment by elea** [comment]
Texted Danelle to ask whether DivCare had our 2017 dates down yet. Will follow up with email shortly

**Comment by theholla** [comment]
Let me know if you need leads on this-- I know some folks.

**Comment by elea** [comment]
Danelle / DivCare emailed us back with quotes for the week and I've forwarded them to Reid, FYI
