### ISSUE TITLE
🎪 Plan a Party

### ISSUE THREAD

**Issue by reidab** [osbridge/planning#336]
We're thinking of following a similar format to last year's party: Thursday night, on-site at the Eliot center, with multiple activity zones. We need someone to take the lead on making the party great.

* [x] Decide on what makes a party a party
* [ ] Make a bunch more tasks describing party logistics
* [x] Gather all the party components
* [x] Assemble party components
* [x] Par-ty 👯‍♂️

**Comment by elea** [comment]
FYI have emailed Elephant's requesting food donation for the party. Requested enough for 200 attendees and they should respond back to sponsorship@opensourcebridge.org within 15 business days.

**Comment by ChrisFreeman** [comment]
I know a manager at the Elephants Corbett St store. I've asked if they can look into Elea's request.

**Comment by reidab** [comment]
Ask Happy Mountain Kombucha for donations

**Comment by elea** [comment]
FYI today I went on a procrastinating/donation request spree and have also pinged Sizzle Pie and Crave Catering via their donation forms. All of them use Thursday's name as the contact and the OSB sponsorship email.

**Comment by reidab** [comment]
from past years we have:
- soldering supplies
- lockpicking supplies
- some games

maybe acquire:
- facepainting
- tarot
- hair chalk
- piñatas
- games (borrowed from community or game store)

**Comment by thejensen** [comment]
I got a lead with New Seasons -- Noland (noland.chaliha@newseasonsmarket.com) may be interested in donating non-alcoholic beverages / snacks to Thurs party. Emailed him back / will call him tomorrow during the day. We'll see!
