### ISSUE TITLE
💌 Send daily newsletters during the conference

### ISSUE THREAD

**Issue by reidab** [osbridge/planning#343]
We send a daily newsletter to attendees each day of the conference. This is sent via Eventbrite.

1. Review [a previous year's newsletter outline and the archive of sent newsletters](http://stumptownsyndicate.org/wiki/Open_Source_Bridge/2014/DailyNewsletter)
2. Write a newsletter daily
3. Send via Eventbrite

**Comment by elea** [comment]
Scheduled for both Eventbrite and blog
