### ISSUE TITLE
💌 Send pre-conference email to attendees

### ISSUE THREAD

**Issue by reidab** [osbridge/planning#344]
We send a pre-conference email to all registered attendees, reminding them of things they might need to know. This message should be sent via Eventbrite.

You can review past messages for reference/inspiration: [2014 outline](http://stumptownsyndicate.org/wiki/Open_Source_Bridge/2014/LastMinuteEmailReminders), [2014 email](http://etherpad.stumptownsyndicate.org/p/2014OSBAttendeeReminder), [2015 email](http://stumptownsyndicate.org/wiki/Open_Source_Bridge/2015/Daily_Newsletter/Pre-Conference)

**Comment by thejensen** [comment]
@capnleela i have a calendar reminder up for myself; if you'd like to be invited to it, what's your email address?
