### ISSUE TITLE
💌 Send pre-conference email to speakers

### ISSUE THREAD

**Issue by reidab** [osbridge/planning#345]
We send a pre-conference email to speakers, reminding them of things they might need to know. This message should be sent via MailChimp.

You can review past messages for reference/inspiration: [2014 outline](http://stumptownsyndicate.org/wiki/Open_Source_Bridge/2014/LastMinuteEmailReminders), [2014 email](http://us2.campaign-archive2.com/?u=46d72c6c2733a75b61cfcf5ad&id=c8e044e2f6&e=%5BUNIQID%5D), [2015 email](http://us2.campaign-archive1.com/?u=46d72c6c2733a75b61cfcf5ad&id=7179743cac)

**Comment by aeschright** [comment]
We probably want to do this a few times: now that the schedule is out, again about two weeks before the conference, and one last time the week before
