### ISSUE TITLE
🌲 See if Eric H. is interested in organizing a hike

### ISSUE THREAD

**Issue by reidab** [osbridge/planning#349]
We heard that one of @ericholscher's favorite parts of running Write the Docs was planning the pre-conference hike. It was suggested that we ask if he'd like to organize a pre- or post- conference hike for OSB this year.

**Comment by ericholscher** [comment]
I'd be curious about it. For reference: http://www.writethedocs.org/conf/na/2017/hike/ -- I might also be running the same pre-conf hike for Pycon, so by the time OSB rolls around it should be pretty well ironed out :)

The main conflict I have is I might be in SF on Mon the 19th for Sustain Conf (https://sustainoss.org/) , but not 100% sure on that.

**Comment by ericholscher** [comment]
Any more info here? I'm on the fence about going to Sustain, but curious how serious y'all are on this.
