### ISSUE TITLE
🎙 Promote conference on Recompiler podcast

### ISSUE THREAD

**Issue by reidab** [osbridge/planning#353]
The Recompiler is a media sponsor and offered to distribute a discount code for us on their podcast. 

* [x] Generate a discount code
* [x] Write a bit of copy (?)
* [x] Send them to @christi3k
* [x] Follow up to make sure it gets on there

**Comment by gabelula** [comment]
@aeschright is this something you can do?

**Comment by aeschright** [comment]
@gabelula Yep, we can add that to the podcast announcements as soon as we have the things listed above.

**Comment by reidab** [comment]
The podcast discount code is `podcast`

**Comment by thejensen** [comment]
Copy: 
Spoken -- Attendance Promotion (e.g. podcast)

Hi! I’m _myName_ and I’d like to shout out Open Source Bridge 2017, a community conference in its 9th year in Portland, OR. 

Every year, OSB hosts an audience of 500 developers, hardware hackers, community organizers, and you! This year, we have 5 tracks: activism, culture, hacks, practice and theory. At Open Source Bridge, you’ll see amazing speakers, have the chance to hack in the Hacker Lounge, meet new friends and potential collaborators. 

Open Source Bridge will be held from June 20th to the 23rd at The Eliot Center in downtown Portland, Oregon. For more information, to register to attend, or to volunteer, go to opensourcebridge.org. Psst, if you use the promo code PODCAST during eventbrite registration, you’ll get $50 off.

Sent request to Christie via slack

**Comment by gabelula** [comment]
Done.
