### ISSUE TITLE
🎙 Reach out to podcasts that might promote OSB

### ISSUE THREAD

**Issue by reidab** [osbridge/planning#354]
Ideas: 

* [ ] Greater than Code
* [ ] Recompiler
* ???

**Comment by reidab** [comment]
https://griffio.github.io/tech-podcasts/

**Comment by reidab** [comment]
Other suggestions from Twitter:

- [ ] The Changelog
- [ ] Request for Commits
- [ ] CodeNewbies
- [ ] Track Changes
- [ ] Recode
- [ ] Tech Done Right
- [ ] The Frontside
- [ ] BSD Now

**Comment by thejensen** [comment]
I managed to get a spot on Spawn On Me a couple weeks ago to promote our CFP. I can do that again for general promotion.
