### ISSUE TITLE
💰 Get financial sponsors

### ISSUE THREAD

**Issue by elea** [osbridge/planning#355]
- [x] Make a list of sponsors we want to reach out to
- [x] Add contact info to sponsor spreadsheet
- [x] Reach out to sponsors
- [ ] Get sponsors to commit

**Comment by thursdayb** [comment]
@reidab Can you add ClientJoy as a sponsor? They're an in-kind sponsor for the speaker gifts. The logo should be the same as last year.

**Comment by reidab** [comment]
@thursdayb added! Does the person who gave us the diversity travel scholarship want any credit for them or their company?
