### ISSUE TITLE
👋 Hold informational meeting for potential volunteers

### ISSUE THREAD

**Issue by reidab** [osbridge/planning#359]
We're interested in holding some in-person info sessions for potential on-site volunteers.

Here's some information from times we've done these in the past:

* 2010: https://calagator.org/events/1250458716
* 2012: https://calagator.org/events/1250462352
* 2013: https://calagator.org/events/1250464221 + https://groups.google.com/forum/#!topic/osbridge/db7BIyKGlxo

**Comment by gabelula** [comment]
Hi @kalina , @ChrisFreeman , how are you going with this? Any idea when and where?

**Comment by ChrisFreeman** [comment]
I have not been working on it.

**Comment by reidab** [comment]
@kalina had mentioned that he's be willing to run some of these at the SE Lucky Lab. I'd say we should wait until after the volunteer app is live and then schedule one in the following week or so.

**Comment by elea** [comment]
Held on Tuesday.
