### ISSUE TITLE
📝 Design volunteer recruitment flyers

### ISSUE THREAD

**Issue by reidab** [osbridge/planning#360]
We need some simple flyers to put up in schools and other places we think volunteers might come from.

Basic requirements:

- [x] conference date
- [x] info on how one can get free tickets by volunteering, per http://opensourcebridge.org/get-involved
- [x] able to be printed on letter-sized paper, either full page or half page
- [x] designed to be effective even when printed in black and white

**Comment by thejensen** [comment]
make direct edits here: 

https://www.canva.com/design/DACRs5xEHv0/share?role=EDITOR&token=-lTMRvKChLxEhxzxiik73Q&utm_content=DACRs5xEHv0&utm_campaign=designshare&utm_medium=link&utm_source=sharebutton

**Comment by thejensen** [comment]
[OSB_pls_volunteer_flyer.pdf](https://github.com/osbridge/planning/files/985233/OSB_pls_volunteer_flyer.pdf)
^that's it!
