### ISSUE TITLE
🎗 Count and wash the lanyards; maybe order more

### ISSUE THREAD

**Issue by reidab** [osbridge/planning#366]
- [x] Retrieve lanyards from the storage unit
- [x] Deliver lanyards to @thursdayb or @kcomandich for counting/washing
- [ ] Deliver lanyards to the Eliot Center for use

**Comment by reidab** [comment]
@thursdayb Do we have a rough count of these? I think we need to put in an order soon if we want more.

**Comment by thursdayb** [comment]
Red — 140
Yellow — 80
Blue — 300

I don't think we need more.
