### ISSUE TITLE
👐 Look into massage

### ISSUE THREAD

**Issue by reidab** [osbridge/planning#368]
We've had massage folks come to massage folks before. This was well liked. Are the people we had before available? Do we want to do this again?

**Comment by thursdayb** [comment]
Talked to Charise and she's onboard

**Comment by aeschright** [comment]
Update from Charise:
On Tuesday, I'll be available 11-1, 2:30-4:30, and 5:30-6:30. On Weds and Thurs, I'll be available 9-11, 11:30-1, 2:30-4:30, and 5:30-6:30
