### ISSUE TITLE
Email our speakers to tell them to promote the schedule

### ISSUE THREAD

**Issue by gabelula** [osbridge/planning#371]

**Comment by capnleela** [comment]
started a document. https://docs.google.com/document/d/18kzHsKCyDA-sscNZCfSu2vziff3E-1ooLMm9uzYD94o/edit?usp=sharing

**Comment by elea** [comment]
@reidab Tagging you into this so we can remember to add speaker codes to the email we want to send out...

**Comment by aeschright** [comment]
I think this is all done with the email that went out yesterday.
