### ISSUE TITLE
email people that volunteered other years

### ISSUE THREAD

**Issue by gabelula** [osbridge/planning#372]

**Comment by gabelula** [comment]
@ChrisFreeman Can we coordinate to follow through with volunteers? I want to help with this but not sure what is already done and what is not.

**Comment by gabelula** [comment]
Thanks @ChrisFreeman !

**Comment by ChrisFreeman** [comment]
Sent to 2015, 2016, 2017 active participants plus all on the google intake form. Approx. 209 emails sent.  Closing.
