### ISSUE TITLE
Looks like some "smart quotes" sneaked into the HTML for the badges

### ISSUE THREAD

**Issue by znmeb** [osbridge/planning#374]
I just posted an "I'm Speaking" badge to my blog (https://www.algocompsynth.com). It's a Hugo site and the rendering process choked on the HTML for the badge:

```
<a href=”http://opensourcebridge.org/?ref=2017speak125″ >
<img src=”http://opensourcebridge.org/badges/2017/speak125@2x.png” 
alt=”I’m speaking at Open Source Bridge – June 20-23, 2017 – Portland, OR” 
width=”125″ height=”125″ border=”0″ /></a>
```

Those look like "smart quotes" - I'm not sure how they got there, but I had to change them to plain old `"` characters to get my blog to render.

**Comment by gabelula** [comment]
@reidab Is this something you can take a look for this year?
