### ISSUE TITLE
Get in touch with Holli and renegotiate rooms

### ISSUE THREAD

**Issue by elea** [osbridge/planning#375]
- [x] See if we can renegotiate our contract so that we're using less rooms?
- [x] Schedule venue walkthrough

**Comment by elea** [comment]
FYI @capnleela says she can take this on!

**Comment by elea** [comment]
To-do: get back to Holli with the rooms that we want to remove from the contract!

**Comment by reidab** [comment]
We walked through! 

Here are the changes I think we want to make:

Buchan Room
- We have this scheduled until 12am Tuesday–Thursday, but we actually only need it until 10pm Tuesday–Wednesday and 11pm on Thursday

All Classrooms
- Like the Buchan, we only need these until 10pm Tuesday–Wednesday and 11pm on Thursday

A201
- Not needed

A108
- Not needed

Sanctuary
- Only needed until 10:30 each morning
- Not needed for Thursday evening 5–8pm timeslot

Kitchen Access
- Not needed

I've also updated the set-up doc with suggested edits

**Comment by reidab** [comment]
Check on nursing space
