### ISSUE TITLE
👶 Check with Eliot Center about space for nursing

### ISSUE THREAD

**Issue by reidab** [osbridge/planning#379]

**Comment by elea** [comment]
Could we designate the single stall restroom for this? We can't really afford to spend any extra $ on rooms at this point, so if that works...I think that might be the best option?

**Comment by thursdayb** [comment]
We can offer space in the quiet room, and if I recall correctly, there's a
corner where we can turn around a chair to create a more private nook.

--
Thursday R. Bram
thursdaybram.com
twitter.com/thursdayb

**Comment by reidab** [comment]
There's a nursery space that we can get access to by asking a sexton. There's also a fridge available in A106 if she wants to store anything.
