### ISSUE TITLE
Review volunteer sign-up process -- suggest improvements if necessary

### ISSUE THREAD

**Issue by thejensen** [osbridge/planning#403]
Put on your UX hat and see if the volunteer sign up process should be tweaked in any serious way.

**Comment by thejensen** [comment]
1) Are we giving away free shirts? I thought not. The first questions asks for shirt size. 
"What size would you like your free volunteer shirt? All volunteers get a special t-shirt to wear during their shift(s). We can't guarentee this size will be available. Your selection will help guide our ordering. Shirts are available in 'straight cut' and 'fitted cut'"

**Comment by thejensen** [comment]
<img width="590" alt="screen shot 2017-06-05 at 8 00 15 pm" src="https://cloud.githubusercontent.com/assets/13670791/26811935/a233e006-4a29-11e7-9683-72d15eb4030a.png">

^appears broken since 'show' and 'hide' buttons dont seem to affect anything

**Comment by thejensen** [comment]
<img width="638" alt="screen shot 2017-06-05 at 8 17 33 pm" src="https://cloud.githubusercontent.com/assets/13670791/26812357/17068a4e-4a2c-11e7-8640-72bbbac01d53.png">

^So many shifts are "full" but have 0/0 required

**Comment by ChrisFreeman** [comment]
Great feedback. The focus will be on fixing errors. Enhancement and UX wishlist items will might have to wait for next year.

**Comment by ChrisFreeman** [comment]
The Show/Hide buttons are primarily for changing the display of all shifts with the "group". Since Hacker Lounge only has one task type, the group buttons are redundant with the Show Shifts button found at the bottom of the task description.  Will note to fold under some of the features (like group buttons) when not needed.

**Comment by elea** [comment]
Other than things mentioned, flow was smooth and it was relatively easy to sign up or drop shifts!

**Comment by gabelula** [comment]
@ChrisFreeman Is there anything else that needs to happen to close this ticket?

**Comment by ChrisFreeman** [comment]
Ok to close. Will incorporate feedback in to the flow.
