### ISSUE TITLE
Tweet / email to get folks into volunteer.opensourcebridge.org (once the UX is reviewed)

### ISSUE THREAD

**Issue by thejensen** [osbridge/planning#404]

**Comment by gabelula** [comment]
Information that needs to go into the tweet:

Volunteer through our http://volunteer.opensourcebridge.org for 8 hours or more to earn a free registration code for this year.

2017 Open Source Bridge is happening June 20-23, 2017 at

Eliot Center (Buchan Building)
1226 SW Salmon Street
Portland, Oregon 97205

**Comment by elea** [comment]
Tweets and Facebook posts have been scheduled
