### ISSUE TITLE
On-site: social media + daily newsletter 

### ISSUE THREAD

**Issue by thejensen** [osbridge/planning#413]

**Comment by elea** [comment]
Wrote and scheduled all the emails in Eventbrite!

**Comment by lehudgins** [comment]
I haven't been involved much but I can help with onsite social media for at
least a day or two.

**Comment by elea** [comment]
Also scheduled all the emails as blog posts. Whee!

**Comment by elea** [comment]
@lehudgins Oooh, which days?

**Comment by lehudgins** [comment]
It's possible, but I'm not promising, that I could come by for some amount
of time mid-day tomorrow. I can definitely do noon-3pm on the 21st
(approximately, I have an appointment earlier in the day). All day on the
22nd.

Also, I can bring my camera and get a few shots.

**Comment by elea** [comment]
Ok, if you could take point on Thursday the 22nd for social media, that'd be awesome! Thanks @lehudgins!

**Comment by lehudgins** [comment]
Absolutely. Can you fill me in on the logins we need? I think I still have
access to Hootsuite but it would be nice to have access to Twitter directly
so that I can add images.

Lauren

**Comment by elea** [comment]
@lehudgins It's Hootsuite, Twitter, and Facebook. I just added you to Tweetdeck, so you should be able to access and manage the OSB twitter account through that and upload photos. We've been neglecting Facebook a little bit, but you're still an Editor admin on our Facebook page as well. If you need direct access to Twitter, I can Slack the pw.

**Comment by lehudgins** [comment]
I think the Hootsuite password has changed since I had the password. Can
you send that to me, or send me the password for Twitter.
