### ISSUE TITLE
Transfer osbridge.org to our registrar

### ISSUE THREAD

**Issue by reidab** [osbridge/planning#42]
When attempting to transfer osbridge.org, all of the owner approvals happened fine, but Dreamhost somehow denied the transfer with

```
Transfer Refused by Registrar (Queue Message #1921670)
```

**Comment by akf** [comment]
bump. :-)

**Comment by kcomandich** [comment]
It somehow got renewed, wherever it is:

Domain Name:OSBRIDGE.ORG
Registry Expiry Date: 2016-02-01T18:52:13Z
Registrant Organization:A Happy DreamHost Customer

**Comment by reidab** [comment]
I just kicked off another instance of this transfer, just in case that triggers something on Dreamhost's end.

**Comment by gabelula** [comment]
This seems to be a VERY OLD issue. I'm closing it and saying bye bye to osbridge.org . 

Bye bye osbridge.org !
