### ISSUE TITLE
Create feedback survey

### ISSUE THREAD

**Issue by aeschright** [osbridge/planning#424]
It should ask nice questions

**Comment by elea** [comment]
Is this for the attendees? (Assuming yes?) If so, we should create and send out ASAP while things are fresh in everyone's minds!

Also, do we want to ask less nice questions too, for things that weren't so great that we want to change in Year 10?

**Comment by aeschright** [comment]
Yes and yes.

**Comment by aeschright** [comment]
I don't even remember what I meant by "nice" here. I was tired.
