### ISSUE TITLE
Design volunteer flyer for school (and other) bulletin boards

### ISSUE THREAD

**Issue by reidab** [osbridge/planning#52]

**Comment by MartinDesigner** [comment]
![imghome](https://cloud.githubusercontent.com/assets/13809960/9289151/f37dac74-4366-11e5-813e-b8e919acb902.jpg)
Try Createer.com. You can easily design online ads, responsive landing pages and print materials such as flyers, posters, covers, invitations and more. Createer lets you easily share your designs on social media, send them via email, download as HTML, image or PDF. Createer also includes 3,000 predesigned template (look here https://beta2.createer.com/Templates) s and over 250,000 images (illustrations, photos and icons) to work with in its user-friendly drag’n’drop enviroment.
