### ISSUE TITLE
Clean up spam on osbridge wiki

### ISSUE THREAD

**Issue by kcomandich** [osbridge/planning#66]
I cleared out a lot of spam and blocked spam users. I didn't find the best way to check for spam, but checked Recent Changes, Long Pages, [User pages](http://opensourcebridge.org/wiki-raw/index.php?title=Special%3AAllPages&from=&to=&namespace=2).

I added the http://www.mediawiki.org/wiki/Extension:BlockandNuke extension so I could delete pages & block users at once, but it only works for Recent Changes. I had already deleted any recent spam, so I cleared out the older spam by hand.
So I haven't tried that extension yet.

Will keep an eye on Recent Changes to see what appears next. I wasn't able to determine if the spam users were using OpenID or not.

**Comment by kcomandich** [comment]
Well I didn't check back on this, and I discovered tonight that we have a lot of spam again.

**Comment by reidab** [comment]
I tried the BlockAndNuke extension for the recent spam, after adding a few users to its whitelist and verifying that its delete list didn't include anything we didn't want deleted.

I then reviewed the list of all pages and it all seemed OSB-related.

**Comment by kcomandich** [comment]
Thank you! I looked at the delete list and it was very long so I thought I would double-check it tomorrow. Thanks for taking care of it! ✨
