### ISSUE TITLE
Image load failure: i/v4_global_nav_BL.png

### ISSUE THREAD

**Issue by ChrisFreeman** [osbridge/planning#98]
OSB CSS file opensourcebridge.org/common/**osbp_common_v3.css**, line 474, references:

    #menu li.global {
        background: url("i/v4_global_nav_BL.png") no-repeat scroll left bottom #109A8B;
        ...
    }
File not found (404) thrown for http://opensourcebridge.org/common/i/v4_global_nav_BL.png

**Comment by reidab** [comment]
Fixed! (it was supposed to be referencing a gif, not a png)
